/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.batalha.gui;
import com.batalha.common.InterfaceServidor;
import com.batalha.model.Partida;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author aluno
 */
public class TelaLobby extends javax.swing.JFrame {
    private InterfaceServidor servidor;
    private String idSessao;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLobby.class.getName());

    /**
     * Creates new form TelaLobby
     */
    public TelaLobby() {
        this.servidor = servidor;
        this.idSessao = idSessao;
        initComponents();
        atualizarListaPartidas();
    }
    
    private void btnCriarPartidaActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Partida partida = servidor.criarPartida(idSessao);
            JOptionPane.showMessageDialog(this, "Partida criada! ID: " + partida.getId());
            atualizarListaPartidas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao criar partida: " + e.getMessage());
        }
    }
    
    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {
        atualizarListaPartidas();
    }

    // Duplo clique na lista: entrar em uma partida
    private void listaPartidasMouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2) {
            int idx = listaPartidas.getSelectedIndex();
            if (idx >= 0) {
                String selecionado = listaPartidas.getModel().getElementAt(idx);
                Long idPartida = Long.valueOf(selecionado.split(":")[0].replace("ID ","").trim());
                try {
                    servidor.entrarNaPartida(idSessao, idPartida);
                    new TelaPosicionarNavios(servidor, idSessao, idPartida).setVisible(true);
                    this.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro ao entrar na partida: " + e.getMessage());
                }
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLobby().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
